### ISSUE TITLE
Опечатка в главе про дисперсию

### ISSUE THREAD

**Issue by metametamoon** [koreshaSp/probability_theory#35]
Перепутана буква в выражении.
![image](https://github.com/koreshaSp/probability_theory/assets/64495509/69b5af4a-c5a9-49f2-90cc-820b4a00c936)

**Comment by metametamoon** [comment]
Такая же опечатка чуть ниже в конспекте
![image](https://github.com/koreshaSp/probability_theory/assets/64495509/c3d81539-ffdb-4c5a-86a1-264e5e851caa)

**Comment by buyolitsez** [comment]
https://github.com/koreshaSp/probability_theory/pull/31

пофиксил
